# Generated by Django 4.2.28 on 2026-03-29 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('procurement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('contract_type', models.CharField(choices=[('logistics', 'Logistics Contract'), ('supplier_agreement', 'Supplier Agreement'), ('nda', 'Non-Disclosure Agreement'), ('service_agreement', 'Service Agreement'), ('lease', 'Lease Agreement'), ('purchase_agreement', 'Purchase Agreement')], default='supplier_agreement', max_length=25)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('under_review', 'Under Review'), ('expired', 'Expired'), ('terminated', 'Terminated')], default='draft', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('PKR', 'PKR'), ('AED', 'AED'), ('SAR', 'SAR'), ('INR', 'INR'), ('CNY', 'CNY')], default='USD', max_length=3)),
                ('description', models.TextField(blank=True)),
                ('terms_and_conditions', models.TextField(blank=True)),
                ('auto_renew', models.BooleanField(default=False)),
                ('renewal_period_days', models.PositiveIntegerField(default=0)),
                ('notice_period_days', models.PositiveIntegerField(default=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_compliance_contracts', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='core.tenant')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_contracts', to='procurement.vendor')),
            ],
            options={
                'verbose_name': 'Contract',
                'verbose_name_plural': 'Contracts',
                'ordering': ['-created_at'],
                'unique_together': {('tenant', 'contract_number')},
            },
        ),
        migrations.CreateModel(
            name='TradeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.CharField(max_length=50)),
                ('document_type', models.CharField(choices=[('bill_of_lading', 'Bill of Lading'), ('commercial_invoice', 'Commercial Invoice'), ('packing_list', 'Packing List'), ('certificate_of_origin', 'Certificate of Origin'), ('customs_declaration', 'Customs Declaration'), ('letter_of_credit', 'Letter of Credit'), ('insurance_certificate', 'Insurance Certificate')], default='bill_of_lading', max_length=25)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('archived', 'Archived')], default='draft', max_length=15)),
                ('origin_country', models.CharField(blank=True, max_length=100)),
                ('destination_country', models.CharField(blank=True, max_length=100)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('PKR', 'PKR'), ('AED', 'AED'), ('SAR', 'SAR'), ('INR', 'INR'), ('CNY', 'CNY')], default='USD', max_length=3)),
                ('description', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_trade_documents', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_documents', to='core.tenant')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trade_documents', to='procurement.vendor')),
            ],
            options={
                'verbose_name': 'Trade Document',
                'verbose_name_plural': 'Trade Documents',
                'ordering': ['-created_at'],
                'unique_together': {('tenant', 'document_number')},
            },
        ),
        migrations.CreateModel(
            name='TradeDocumentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_description', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=12)),
                ('unit_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('trade_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='contracts.tradedocument')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SustainabilityReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_number', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('report_type', models.CharField(choices=[('carbon_footprint', 'Carbon Footprint'), ('ethical_sourcing', 'Ethical Sourcing'), ('waste_management', 'Waste Management'), ('energy_consumption', 'Energy Consumption'), ('water_usage', 'Water Usage')], default='carbon_footprint', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('reviewed', 'Reviewed'), ('approved', 'Approved'), ('published', 'Published')], default='draft', max_length=15)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('total_carbon_footprint', models.DecimalField(decimal_places=2, default=0, help_text='Total CO2 emissions in metric tons', max_digits=12)),
                ('carbon_offset', models.DecimalField(decimal_places=2, default=0, help_text='Carbon offset in metric tons', max_digits=12)),
                ('sustainability_score', models.DecimalField(decimal_places=2, default=0, help_text='Score from 0 to 100', max_digits=5)),
                ('description', models.TextField(blank=True)),
                ('recommendations', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sustainability_reports', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sustainability_reports', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Sustainability Report',
                'verbose_name_plural': 'Sustainability Reports',
                'ordering': ['-created_at'],
                'unique_together': {('tenant', 'report_number')},
            },
        ),
        migrations.CreateModel(
            name='SustainabilityMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_name', models.CharField(max_length=255)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('target', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('variance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='contracts.sustainabilityreport')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ContractDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('file_reference', models.CharField(blank=True, max_length=500)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='contracts.contract')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compliance_number', models.CharField(max_length=50)),
                ('regulation_name', models.CharField(max_length=255)),
                ('regulation_type', models.CharField(choices=[('fda', 'FDA'), ('hazmat', 'HazMat'), ('gdpr', 'GDPR'), ('iso', 'ISO'), ('customs', 'Customs'), ('environmental', 'Environmental'), ('labor', 'Labor'), ('trade_sanctions', 'Trade Sanctions'), ('other', 'Other')], default='other', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_compliance', 'In Compliance'), ('non_compliant', 'Non-Compliant'), ('under_review', 'Under Review'), ('expired', 'Expired')], default='draft', max_length=20)),
                ('compliance_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('corrective_action', models.TextField(blank=True)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_compliance_records', to=settings.AUTH_USER_MODEL)),
                ('responsible_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_responsibilities', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_records', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Compliance Record',
                'verbose_name_plural': 'Compliance Records',
                'ordering': ['-created_at'],
                'unique_together': {('tenant', 'compliance_number')},
            },
        ),
        migrations.CreateModel(
            name='ComplianceCheckItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_item', models.CharField(max_length=255)),
                ('result', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('na', 'N/A'), ('pending', 'Pending')], default='pending', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('compliance_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_items', to='contracts.compliancerecord')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('license_type', models.CharField(choices=[('import', 'Import License'), ('export', 'Export License'), ('transit', 'Transit Permit'), ('special_permit', 'Special Permit'), ('bonded_warehouse', 'Bonded Warehouse License'), ('customs_broker', 'Customs Broker License')], default='import', max_length=20)),
                ('issuing_authority', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('expiring_soon', 'Expiring Soon'), ('expired', 'Expired'), ('suspended', 'Suspended'), ('revoked', 'Revoked')], default='draft', max_length=20)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('license_reference', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('renewal_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_licenses', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='core.tenant')),
            ],
            options={
                'verbose_name': 'License',
                'verbose_name_plural': 'Licenses',
                'ordering': ['-created_at'],
                'unique_together': {('tenant', 'license_number')},
            },
        ),
    ]
