# Generated by Django 4.2.28 on 2026-03-26 20:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('procurement', '0001_initial'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CollaborativePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_number', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('plan_type', models.CharField(choices=[('sales_plan', 'Sales Plan'), ('marketing_plan', 'Marketing Plan'), ('finance_plan', 'Finance Plan'), ('operations_plan', 'Operations Plan'), ('consensus', 'Consensus Plan')], default='sales_plan', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('review', 'Under Review'), ('approved', 'Approved'), ('finalized', 'Finalized')], default='draft', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_collaborative_plans', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_collaborative_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SafetyStockCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculation_number', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('calculation_method', models.CharField(choices=[('fixed', 'Fixed Quantity'), ('percentage', 'Percentage of Demand'), ('statistical', 'Statistical (Z-score)'), ('demand_based', 'Demand-Based')], default='statistical', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('calculated', 'Calculated'), ('approved', 'Approved'), ('applied', 'Applied')], default='draft', max_length=20)),
                ('calculation_date', models.DateField()),
                ('default_service_level', models.DecimalField(decimal_places=2, default=95.0, help_text='Default service level percentage (e.g. 95.00)', max_digits=5)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_safety_stock_calcs', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_safety_stock_calcs', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safety_stock_calculations', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('tenant', 'calculation_number')},
            },
        ),
        migrations.CreateModel(
            name='SeasonalityProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('jan_factor', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('feb_factor', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('mar_factor', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('apr_factor', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('may_factor', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('jun_factor', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('jul_factor', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('aug_factor', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('sep_factor', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('oct_factor', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('nov_factor', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('dec_factor', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_seasonality_profiles', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasonality_profiles', to='procurement.item')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasonality_profiles', to='core.tenant')),
            ],
            options={
                'ordering': ['item__name'],
                'unique_together': {('tenant', 'item')},
            },
        ),
        migrations.CreateModel(
            name='SalesForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_number', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('forecast_method', models.CharField(choices=[('moving_average', 'Moving Average'), ('exponential_smoothing', 'Exponential Smoothing'), ('linear_regression', 'Linear Regression'), ('manual', 'Manual Entry')], default='moving_average', max_length=30)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('active', 'Active'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_forecasts', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_forecasts', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_forecasts', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('tenant', 'forecast_number')},
            },
        ),
        migrations.CreateModel(
            name='PromotionalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('event_type', models.CharField(choices=[('holiday', 'Holiday'), ('promotion', 'Promotion'), ('clearance', 'Clearance'), ('launch', 'Product Launch'), ('seasonal', 'Seasonal')], default='promotion', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('impact_factor', models.DecimalField(decimal_places=2, default=1.0, help_text='Multiplier for demand during this event (e.g. 1.5 = 50% increase)', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_promotional_events', to=settings.AUTH_USER_MODEL)),
                ('seasonality_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='demand_planning.seasonalityprofile')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotional_events', to='core.tenant')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='PlanLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_items', to='procurement.item')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='demand_planning.collaborativeplan')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PlanComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_comments', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='demand_planning.collaborativeplan')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ForecastLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecasted_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('actual_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('confidence_level', models.DecimalField(decimal_places=2, default=0, help_text='Confidence level percentage (0-100)', max_digits=5)),
                ('notes', models.TextField(blank=True)),
                ('forecast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='demand_planning.salesforecast')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forecast_items', to='procurement.item')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='collaborativeplan',
            name='forecast',
            field=models.ForeignKey(blank=True, help_text='Linked sales forecast, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collaborative_plans', to='demand_planning.salesforecast'),
        ),
        migrations.AddField(
            model_name='collaborativeplan',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborative_plans', to='core.tenant'),
        ),
        migrations.CreateModel(
            name='SafetyStockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_demand', models.DecimalField(decimal_places=2, default=0, help_text='Average daily/weekly demand', max_digits=12)),
                ('demand_std_dev', models.DecimalField(decimal_places=2, default=0, help_text='Standard deviation of demand', max_digits=12)),
                ('lead_time_days', models.PositiveIntegerField(default=0)),
                ('lead_time_std_dev', models.DecimalField(decimal_places=2, default=0, help_text='Standard deviation of lead time in days', max_digits=8)),
                ('service_level_pct', models.DecimalField(decimal_places=2, default=95.0, max_digits=5)),
                ('calculated_safety_stock', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('current_stock', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('recommended_reorder_point', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('calculation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='demand_planning.safetystockcalculation')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safety_stock_items', to='procurement.item')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safety_stock_items', to='inventory.warehouse')),
            ],
            options={
                'ordering': ['item__name'],
                'unique_together': {('calculation', 'item', 'warehouse')},
            },
        ),
        migrations.CreateModel(
            name='DemandSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_number', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('signal_type', models.CharField(choices=[('market_trend', 'Market Trend'), ('competitor_action', 'Competitor Action'), ('weather', 'Weather'), ('economic_indicator', 'Economic Indicator'), ('social_media', 'Social Media'), ('customer_feedback', 'Customer Feedback'), ('pos_data', 'POS Data')], default='market_trend', max_length=30)),
                ('impact_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('new', 'New'), ('analyzed', 'Analyzed'), ('incorporated', 'Incorporated'), ('dismissed', 'Dismissed')], default='new', max_length=20)),
                ('estimated_impact_pct', models.DecimalField(decimal_places=2, default=0, help_text='Estimated demand impact percentage (positive=increase, negative=decrease)', max_digits=7)),
                ('signal_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=255)),
                ('analyzed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analyzed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyzed_demand_signals', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_demand_signals', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(blank=True, help_text='Specific item affected, if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demand_signals', to='procurement.item')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demand_signals', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('tenant', 'signal_number')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='collaborativeplan',
            unique_together={('tenant', 'plan_number')},
        ),
    ]
