# Generated by Django 4.2.28 on 2026-03-28 20:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('oms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
        ('procurement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnAuthorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rma_number', models.CharField(max_length=50)),
                ('return_type', models.CharField(choices=[('exchange', 'Exchange'), ('refund', 'Refund'), ('repair', 'Repair'), ('store_credit', 'Store Credit')], default='refund', max_length=20)),
                ('reason_category', models.CharField(choices=[('defective', 'Defective'), ('wrong_item', 'Wrong Item'), ('damaged', 'Damaged'), ('not_as_described', 'Not As Described'), ('changed_mind', 'Changed Mind'), ('other', 'Other')], default='defective', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('receiving', 'Receiving'), ('received', 'Received'), ('closed', 'Closed'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('requested_date', models.DateField(blank=True, null=True)),
                ('approved_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_rmas', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_rmas', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_authorizations', to='oms.customer')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_authorizations', to='oms.order')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_authorizations', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Return Merchandise Authorization',
                'verbose_name_plural': 'Return Merchandise Authorizations',
                'ordering': ['-created_at'],
                'unique_together': {('tenant', 'rma_number')},
            },
        ),
        migrations.CreateModel(
            name='WarrantyClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_number', models.CharField(max_length=50)),
                ('claim_type', models.CharField(choices=[('manufacturer_warranty', 'Manufacturer Warranty'), ('supplier_warranty', 'Supplier Warranty'), ('extended_warranty', 'Extended Warranty')], default='manufacturer_warranty', max_length=25)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('settled', 'Settled'), ('denied', 'Denied'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('warranty_start_date', models.DateField(blank=True, null=True)),
                ('warranty_end_date', models.DateField(blank=True, null=True)),
                ('claim_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('settlement_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('PKR', 'PKR'), ('AED', 'AED'), ('SAR', 'SAR'), ('INR', 'INR'), ('CNY', 'CNY')], default='USD', max_length=3)),
                ('description', models.TextField(blank=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_warranty_claims', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warranty_claims', to='procurement.item')),
                ('rma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warranty_claims', to='returns.returnauthorization')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warranty_claims', to='core.tenant')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warranty_claims', to='procurement.vendor')),
            ],
            options={
                'verbose_name': 'Warranty Claim',
                'verbose_name_plural': 'Warranty Claims',
                'ordering': ['-created_at'],
                'unique_together': {('tenant', 'claim_number')},
            },
        ),
        migrations.CreateModel(
            name='WarrantyClaimItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=12)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claim_items', to='returns.warrantyclaim')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='RMALineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=12)),
                ('reason', models.TextField(blank=True)),
                ('condition', models.CharField(choices=[('new', 'New'), ('used', 'Used'), ('damaged', 'Damaged'), ('defective', 'Defective')], default='used', max_length=15)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rma_line_items', to='procurement.item')),
                ('rma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='returns.returnauthorization')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ReturnPortalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_portal_enabled', models.BooleanField(default=False)),
                ('return_window_days', models.PositiveIntegerField(default=30)),
                ('requires_approval', models.BooleanField(default=True)),
                ('auto_generate_labels', models.BooleanField(default=False)),
                ('restocking_fee_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('return_policy_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='return_portal_settings', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Return Portal Settings',
                'verbose_name_plural': 'Return Portal Settings',
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_number', models.CharField(max_length=50)),
                ('refund_type', models.CharField(choices=[('full', 'Full'), ('partial', 'Partial'), ('store_credit', 'Store Credit')], default='full', max_length=20)),
                ('refund_method', models.CharField(choices=[('original_payment', 'Original Payment'), ('bank_transfer', 'Bank Transfer'), ('store_credit', 'Store Credit'), ('check', 'Check')], default='original_payment', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('PKR', 'PKR'), ('AED', 'AED'), ('SAR', 'SAR'), ('INR', 'INR'), ('CNY', 'CNY')], default='USD', max_length=3)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('processed_date', models.DateField(blank=True, null=True)),
                ('transaction_reference', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_refunds', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_refunds', to=settings.AUTH_USER_MODEL)),
                ('rma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='returns.returnauthorization')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('tenant', 'refund_number')},
            },
        ),
        migrations.CreateModel(
            name='Disposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disposition_number', models.CharField(max_length=50)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=12)),
                ('condition_received', models.CharField(choices=[('new', 'New'), ('like_new', 'Like New'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('damaged', 'Damaged'), ('defective', 'Defective')], default='good', max_length=15)),
                ('disposition_decision', models.CharField(blank=True, choices=[('restock', 'Restock'), ('refurbish', 'Refurbish'), ('repair', 'Repair'), ('scrap', 'Scrap'), ('return_to_supplier', 'Return to Supplier'), ('donate', 'Donate')], max_length=25)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('inspecting', 'Inspecting'), ('decided', 'Decided'), ('processing', 'Processing'), ('completed', 'Completed')], default='pending', max_length=15)),
                ('inspection_notes', models.TextField(blank=True)),
                ('decision_notes', models.TextField(blank=True)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_dispositions', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_dispositions', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispositions', to='procurement.item')),
                ('rma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispositions', to='returns.returnauthorization')),
                ('rma_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispositions', to='returns.rmalineitem')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispositions', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('tenant', 'disposition_number')},
            },
        ),
    ]
