# Generated by Django 4.2.28 on 2026-03-31 19:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tms', '0001_initial'),
        ('oms', '0001_initial'),
        ('core', '0001_initial'),
        ('procurement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(max_length=50)),
                ('current_status', models.CharField(choices=[('processing', 'Processing'), ('shipped', 'Shipped'), ('in_transit', 'In Transit'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('delayed', 'Delayed'), ('returned', 'Returned'), ('cancelled', 'Cancelled')], default='processing', max_length=20)),
                ('estimated_delivery', models.DateField(blank=True, null=True)),
                ('actual_delivery', models.DateField(blank=True, null=True)),
                ('last_location', models.CharField(blank=True, max_length=255)),
                ('carrier_name', models.CharField(blank=True, max_length=255)),
                ('carrier_tracking_url', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_order_trackings', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_trackings', to='oms.order')),
            ],
            options={
                'verbose_name': 'Order Tracking',
                'verbose_name_plural': 'Order Trackings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PortalAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=50)),
                ('display_name', models.CharField(max_length=255)),
                ('portal_email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('pending', 'Pending'), ('closed', 'Closed')], default='pending', max_length=15)),
                ('preferred_language', models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('de', 'German'), ('ar', 'Arabic'), ('ur', 'Urdu'), ('zh', 'Chinese')], default='en', max_length=10)),
                ('billing_address', models.TextField(blank=True)),
                ('shipping_address', models.TextField(blank=True)),
                ('payment_method', models.CharField(choices=[('credit_card', 'Credit Card'), ('bank_transfer', 'Bank Transfer'), ('paypal', 'PayPal'), ('cod', 'Cash on Delivery'), ('store_credit', 'Store Credit')], default='bank_transfer', max_length=20)),
                ('payment_reference', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_portal_accounts', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_accounts', to='oms.customer')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_accounts', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Portal Account',
                'verbose_name_plural': 'Portal Accounts',
                'ordering': ['-created_at'],
                'unique_together': {('tenant', 'account_number')},
            },
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('order_issue', 'Order Issue'), ('delivery_issue', 'Delivery Issue'), ('billing', 'Billing'), ('product_inquiry', 'Product Inquiry'), ('return_request', 'Return Request'), ('general', 'General'), ('complaint', 'Complaint')], default='general', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('waiting_on_customer', 'Waiting on Customer'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('reopened', 'Reopened')], default='open', max_length=25)),
                ('description', models.TextField()),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_support_tickets', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_support_tickets', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets', to='oms.order')),
                ('portal_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to='portal.portalaccount')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Support Ticket',
                'verbose_name_plural': 'Support Tickets',
                'ordering': ['-created_at'],
                'unique_together': {('tenant', 'ticket_number')},
            },
        ),
        migrations.CreateModel(
            name='TrackingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('shipped', 'Shipped'), ('in_transit', 'In Transit'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('delayed', 'Delayed'), ('returned', 'Returned'), ('cancelled', 'Cancelled')], default='processing', max_length=20)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('tracking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_events', to='portal.ordertracking')),
            ],
            options={
                'ordering': ['-event_date'],
            },
        ),
        migrations.CreateModel(
            name='TicketMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=255)),
                ('sender_type', models.CharField(choices=[('customer', 'Customer'), ('agent', 'Agent'), ('system', 'System')], default='customer', max_length=10)),
                ('message', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='portal.supportticket')),
            ],
            options={
                'ordering': ['sent_at'],
            },
        ),
        migrations.AddField(
            model_name='ordertracking',
            name='portal_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_trackings', to='portal.portalaccount'),
        ),
        migrations.AddField(
            model_name='ordertracking',
            name='shipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_trackings', to='tms.shipment'),
        ),
        migrations.AddField(
            model_name='ordertracking',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_trackings', to='core.tenant'),
        ),
        migrations.CreateModel(
            name='PortalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.CharField(max_length=50)),
                ('document_type', models.CharField(choices=[('invoice', 'Invoice'), ('proof_of_delivery', 'Proof of Delivery'), ('contract', 'Contract'), ('packing_list', 'Packing List'), ('credit_note', 'Credit Note'), ('statement', 'Statement'), ('certificate', 'Certificate')], default='invoice', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=15)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_documents', to='oms.order')),
                ('portal_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_documents', to='portal.portalaccount')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_documents', to='core.tenant')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_portal_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Portal Document',
                'verbose_name_plural': 'Portal Documents',
                'ordering': ['-created_at'],
                'unique_together': {('tenant', 'document_number')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='ordertracking',
            unique_together={('tenant', 'tracking_number')},
        ),
        migrations.CreateModel(
            name='CatalogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalog_number', models.CharField(max_length=50)),
                ('portal_name', models.CharField(max_length=255)),
                ('portal_description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('PKR', 'PKR'), ('AED', 'AED'), ('SAR', 'SAR'), ('INR', 'INR'), ('CNY', 'CNY')], default='USD', max_length=3)),
                ('stock_status', models.CharField(choices=[('in_stock', 'In Stock'), ('low_stock', 'Low Stock'), ('out_of_stock', 'Out of Stock'), ('pre_order', 'Pre-Order'), ('discontinued', 'Discontinued')], default='in_stock', max_length=15)),
                ('available_quantity', models.PositiveIntegerField(default=0)),
                ('minimum_order_quantity', models.PositiveIntegerField(default=1)),
                ('lead_time_days', models.PositiveIntegerField(default=0)),
                ('image_url', models.URLField(blank=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_catalog_items', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_catalog_entries', to='procurement.item')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_items', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Catalog Item',
                'verbose_name_plural': 'Catalog Items',
                'ordering': ['-created_at'],
                'unique_together': {('tenant', 'catalog_number')},
            },
        ),
    ]
