# Generated by Django 4.2.28 on 2026-03-22 20:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('procurement', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryValuation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valuation_number', models.CharField(max_length=50)),
                ('valuation_method', models.CharField(choices=[('fifo', 'FIFO (First In, First Out)'), ('lifo', 'LIFO (Last In, First Out)'), ('weighted_avg', 'Weighted Average')], default='weighted_avg', max_length=20)),
                ('valuation_date', models.DateField()),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_items', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_valuations', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_valuations', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReorderRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reorder_point', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('reorder_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('safety_stock', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('lead_time_days', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('last_triggered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reorder_rules', to='procurement.item')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reorder_rules', to='core.tenant')),
            ],
            options={
                'ordering': ['item__name'],
            },
        ),
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_number', models.CharField(max_length=50)),
                ('adjustment_type', models.CharField(choices=[('write_off', 'Write Off'), ('damage', 'Damage'), ('cycle_count', 'Cycle Count'), ('correction', 'Correction'), ('return', 'Return')], default='correction', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('adjustment_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('adjusted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjusted_stock', to=settings.AUTH_USER_MODEL)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_adjustments', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_adjustments', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50)),
                ('warehouse_type', models.CharField(choices=[('main', 'Main Warehouse'), ('branch', 'Branch Warehouse'), ('transit', 'Transit Warehouse')], default='main', max_length=20)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='core.tenant')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('tenant', 'code')},
            },
        ),
        migrations.CreateModel(
            name='WarehouseTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_number', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('in_transit', 'In Transit'), ('received', 'Received'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('transfer_date', models.DateField(blank=True, null=True)),
                ('received_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_transfers', to=settings.AUTH_USER_MODEL)),
                ('destination_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transfers', to='inventory.warehouse')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_transfers', to=settings.AUTH_USER_MODEL)),
                ('source_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_transfers', to='inventory.warehouse')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_transfers', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('tenant', 'transfer_number')},
            },
        ),
        migrations.CreateModel(
            name='WarehouseTransferItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_requested', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('quantity_sent', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('quantity_received', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_items', to='procurement.item')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.warehousetransfer')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50)),
                ('zone', models.CharField(choices=[('receiving', 'Receiving'), ('storage', 'Storage'), ('picking', 'Picking'), ('shipping', 'Shipping')], default='storage', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_locations', to='core.tenant')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='inventory.warehouse')),
            ],
            options={
                'ordering': ['warehouse', 'zone', 'name'],
                'unique_together': {('tenant', 'warehouse', 'code')},
            },
        ),
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_on_hand', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('quantity_reserved', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('reorder_point', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('reorder_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('safety_stock', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('batch_number', models.CharField(blank=True, default='', max_length=100)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('last_received_date', models.DateTimeField(blank=True, null=True)),
                ('last_issued_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='procurement.item')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_items', to='inventory.warehouselocation')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='core.tenant')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='inventory.warehouse')),
            ],
            options={
                'ordering': ['item__name', 'warehouse__name'],
                'unique_together': {('tenant', 'item', 'warehouse', 'batch_number')},
            },
        ),
        migrations.CreateModel(
            name='StockAdjustmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_before', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('quantity_adjustment', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('quantity_after', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('adjustment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.stockadjustment')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustment_items', to='procurement.item')),
                ('stock_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjustments', to='inventory.stockitem')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='stockadjustment',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='inventory.warehouse'),
        ),
        migrations.CreateModel(
            name='ReorderSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggested_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('current_stock', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('reorder_point', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('dismissed', 'Dismissed'), ('po_created', 'PO Created')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reorder_suggestions', to='procurement.item')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='inventory.reorderrule')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reorder_suggestions', to='core.tenant')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reorder_suggestions', to='inventory.warehouse')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='reorderrule',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reorder_rules', to='inventory.warehouse'),
        ),
        migrations.CreateModel(
            name='InventoryValuationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_on_hand', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('valuation_method', models.CharField(default='weighted_avg', max_length=20)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valuation_items', to='procurement.item')),
                ('valuation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.inventoryvaluation')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valuation_items', to='inventory.warehouse')),
            ],
            options={
                'ordering': ['item__name'],
            },
        ),
        migrations.AddField(
            model_name='inventoryvaluation',
            name='warehouse',
            field=models.ForeignKey(blank=True, help_text='Leave blank for all warehouses.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valuations', to='inventory.warehouse'),
        ),
        migrations.AlterUniqueTogether(
            name='stockadjustment',
            unique_together={('tenant', 'adjustment_number')},
        ),
        migrations.AlterUniqueTogether(
            name='reorderrule',
            unique_together={('tenant', 'item', 'warehouse')},
        ),
        migrations.AlterUniqueTogether(
            name='inventoryvaluation',
            unique_together={('tenant', 'valuation_number')},
        ),
    ]
