# Generated by Django 4.2.28 on 2026-03-25 20:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('procurement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('oms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrier_number', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('contact_person', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('address', models.TextField(blank=True)),
                ('carrier_type', models.CharField(choices=[('ftl', 'Full Truckload (FTL)'), ('ltl', 'Less Than Truckload (LTL)'), ('parcel', 'Parcel'), ('air_freight', 'Air Freight'), ('ocean_freight', 'Ocean Freight'), ('rail', 'Rail'), ('courier', 'Courier')], default='ftl', max_length=20)),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tms_carriers', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('tenant', 'carrier_number')},
            },
        ),
        migrations.CreateModel(
            name='FreightBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_number', models.CharField(max_length=50)),
                ('invoice_number', models.CharField(max_length=100)),
                ('invoice_date', models.DateField()),
                ('due_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('currency', models.CharField(choices=[('USD', 'USD - US Dollar'), ('EUR', 'EUR - Euro'), ('GBP', 'GBP - British Pound'), ('PKR', 'PKR - Pakistani Rupee'), ('AED', 'AED - UAE Dirham'), ('SAR', 'SAR - Saudi Riyal'), ('INR', 'INR - Indian Rupee'), ('CNY', 'CNY - Chinese Yuan')], default='USD', max_length=3)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending Review'), ('approved', 'Approved'), ('disputed', 'Disputed'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('audited_at', models.DateTimeField(blank=True, null=True)),
                ('dispute_reason', models.TextField(blank=True)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('audited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tms_audited_bills', to=settings.AUTH_USER_MODEL)),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freight_bills', to='tms.carrier')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoadPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_number', models.CharField(max_length=50)),
                ('vehicle_type', models.CharField(choices=[('truck_20ft', '20ft Truck'), ('truck_40ft', '40ft Truck'), ('container_20ft', '20ft Container'), ('container_40ft', '40ft Container'), ('van', 'Van'), ('flatbed', 'Flatbed'), ('refrigerated', 'Refrigerated'), ('bulk', 'Bulk Carrier')], default='truck_20ft', max_length=20)),
                ('max_weight', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('max_volume', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('planned_weight', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('planned_volume', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('utilization_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('planned', 'Planned'), ('loading', 'Loading'), ('loaded', 'Loaded'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('planned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tms_load_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_number', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('origin', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('distance_km', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estimated_time_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('transport_mode', models.CharField(choices=[('road', 'Road'), ('air', 'Air'), ('ocean', 'Ocean'), ('rail', 'Rail'), ('multimodal', 'Multimodal')], default='road', max_length=20)),
                ('waypoints', models.TextField(blank=True, help_text='Comma-separated waypoints')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('inactive', 'Inactive')], default='draft', max_length=20)),
                ('fuel_cost_estimate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('toll_cost_estimate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('carrier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routes', to='tms.carrier')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tms_routes', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('tenant', 'route_number')},
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_number', models.CharField(max_length=50)),
                ('origin_address', models.TextField()),
                ('destination_address', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('booked', 'Booked'), ('picked_up', 'Picked Up'), ('in_transit', 'In Transit'), ('at_hub', 'At Hub'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('transport_mode', models.CharField(choices=[('road', 'Road'), ('air', 'Air'), ('ocean', 'Ocean'), ('rail', 'Rail'), ('multimodal', 'Multimodal')], default='road', max_length=20)),
                ('estimated_departure', models.DateTimeField(blank=True, null=True)),
                ('actual_departure', models.DateTimeField(blank=True, null=True)),
                ('estimated_arrival', models.DateTimeField(blank=True, null=True)),
                ('actual_arrival', models.DateTimeField(blank=True, null=True)),
                ('total_weight', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_volume', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tracking_url', models.URLField(blank=True)),
                ('current_location', models.CharField(blank=True, max_length=255)),
                ('special_instructions', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='tms.carrier')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='oms.order')),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='tms.route')),
                ('shipped_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tms_shipments', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tms_shipments', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('tenant', 'shipment_number')},
            },
        ),
        migrations.CreateModel(
            name='ShipmentTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('booked', 'Booked'), ('picked_up', 'Picked Up'), ('in_transit', 'In Transit'), ('at_hub', 'At Hub'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], max_length=20)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tms_tracking_events', to=settings.AUTH_USER_MODEL)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_events', to='tms.shipment')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('weight', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('volume', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment_items', to='procurement.item')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tms.shipment')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='LoadPlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('weight', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('volume', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('load_sequence', models.IntegerField(default=0)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='load_plan_items', to='procurement.item')),
                ('load_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tms.loadplan')),
            ],
            options={
                'ordering': ['load_sequence', 'id'],
            },
        ),
        migrations.AddField(
            model_name='loadplan',
            name='shipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='load_plans', to='tms.shipment'),
        ),
        migrations.AddField(
            model_name='loadplan',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tms_load_plans', to='core.tenant'),
        ),
        migrations.CreateModel(
            name='FreightBillItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('charge_type', models.CharField(choices=[('base_freight', 'Base Freight'), ('fuel_surcharge', 'Fuel Surcharge'), ('handling', 'Handling'), ('insurance', 'Insurance'), ('customs', 'Customs'), ('toll', 'Toll'), ('accessorial', 'Accessorial'), ('other', 'Other')], default='base_freight', max_length=20)),
                ('freight_bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tms.freightbill')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='freightbill',
            name='shipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freight_bills', to='tms.shipment'),
        ),
        migrations.AddField(
            model_name='freightbill',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tms_freight_bills', to='core.tenant'),
        ),
        migrations.CreateModel(
            name='RateCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_number', models.CharField(max_length=50)),
                ('origin', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('transport_mode', models.CharField(choices=[('road', 'Road'), ('air', 'Air'), ('ocean', 'Ocean'), ('rail', 'Rail'), ('multimodal', 'Multimodal')], default='road', max_length=20)),
                ('rate_per_unit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(choices=[('USD', 'USD - US Dollar'), ('EUR', 'EUR - Euro'), ('GBP', 'GBP - British Pound'), ('PKR', 'PKR - Pakistani Rupee'), ('AED', 'AED - UAE Dirham'), ('SAR', 'SAR - Saudi Riyal'), ('INR', 'INR - Indian Rupee'), ('CNY', 'CNY - Chinese Yuan')], default='USD', max_length=3)),
                ('unit_type', models.CharField(choices=[('per_kg', 'Per Kg'), ('per_cbm', 'Per CBM'), ('per_pallet', 'Per Pallet'), ('per_container', 'Per Container'), ('flat_rate', 'Flat Rate'), ('per_mile', 'Per Mile'), ('per_km', 'Per Km')], default='per_kg', max_length=20)),
                ('min_charge', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('max_weight', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('transit_days', models.IntegerField(default=0)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_cards', to='tms.carrier')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tms_rate_cards', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('tenant', 'rate_number')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='loadplan',
            unique_together={('tenant', 'plan_number')},
        ),
        migrations.AlterUniqueTogether(
            name='freightbill',
            unique_together={('tenant', 'bill_number')},
        ),
    ]
